name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  PLATFORMS: linux/arm64
  SOURCE_REPOSITORY: ritz078/transform
  DOCKERHUB_REPOSITORY: helllord/transform

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get-tag.outputs.tag }}
    steps:
      - name: Fetch get_tag.py
        uses: actions/checkout@v4
        with:
          repository: hellbot77/get-tag
          sparse-checkout: get_tag.py
          sparse-checkout-cone-mode: false
      - name: Get Docker image tag
        id: get-tag
        run: >
          python3 get_tag.py ${{ github.event_name != 'workflow_dispatch' && env.DOCKERHUB_REPOSITORY || '""' }}
          --gh-commit ${{ env.SOURCE_REPOSITORY }} >> $GITHUB_OUTPUT

  build-push:
    needs: get-tag
    if: ${{ needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.SOURCE_REPOSITORY }}
          ref: ${{ needs.get-tag.outputs.tag }}
      - name: Apply patch
        run: |
          git fetch --unshallow
          if git ls-remote origin pull/372/head; then
            wget https://raw.githubusercontent.com/ritz078/transform/a03bfe858e161bd1ba897d519ae4432853a92982/.dockerignore
            wget https://raw.githubusercontent.com/ritz078/transform/a03bfe858e161bd1ba897d519ae4432853a92982/Dockerfile
            sed -i '0,/RUN yarn/s//RUN yarn --network-timeout 1000000/' Dockerfile
          fi
      - name: Set Docker Hub username
        id: dockerhub-username
        run: echo "username=${DOCKERHUB_REPOSITORY%%/*}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ steps.dockerhub-username.outputs.username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ needs.get-tag.outputs.tag }}
            ${{ env.DOCKERHUB_REPOSITORY }}:latest

  cancel-action:
    needs: get-tag
    if: ${{ !needs.get-tag.outputs.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel action
        uses: andymckay/cancel-action@0.3
      - name: Wait for cancel
        run: sleep infinity
